services:
  localhost-app:
    image: gprestes/the-internet:latest
    container_name: localhost-app
    ports:
      - "7080:5000"
    restart: always

  playwright-tests:
    image: mcr.microsoft.com/playwright:v1.51.1
    container_name: playwright-tests
    depends_on:
      - localhost-app
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/bin/sh", "-c"]
    command:
      - npm run ${SUITE}
    environment:
      - CI=true
      - WORKERS=${WORKERS}
