name: (Docker-compose) Playwright Regression Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:

  lint:
    runs-on: [ self-hosted, linux, X64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Cache Node.js Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .
        continue-on-error: false

  deploy-and-run:
    if: always()
    needs: [ lint ]
    runs-on: [ self-hosted, linux, X64 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Snapshot folder
        uses: actions/cache@v4
        with:
          path: snapshots
          key: snapshots-${{ runner.os }}-${{ hashFiles('snapshots') }}
          restore-keys: |
            snapshots-${{ runner.os }}-

      - name: Set up Docker Compose
        run: docker compose version

      - name: Deploy app & run tests
        run: docker compose up --abort-on-container-exit

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 1

      - name: Upload Artifacts Directory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts
          path: artifacts
          retention-days: 1

      - name: Cleanup Services
        if: always()
        run: |
          docker compose down

  generate-and-publish-report:
    if: always()
    needs: [ deploy-and-run ]
    runs-on: [ self-hosted, linux, X64 ]

    steps:
      - name: Pull repository
        uses: actions/checkout@v4

      - name: Setup AWS cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Create timestamp
        id: timestampid
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"

      - name: Download Allure Results from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results*
          merge-multiple: true
          path: merged-allure-results

      - name: Download current history files from S3
        run: aws s3 cp s3://mkuznetsov-github/history/ ./merged-allure-results/history --recursive

      - name: Generate Allure report
        run: allure generate ./merged-allure-results

      - name: Backup the history with the latest data
        run: aws s3 cp ./allure-report/history s3://mkuznetsov-github/history/  --recursive

      - name: Deploy html report to S3
        run: aws s3 cp ./allure-report s3://mkuznetsov-github/report/${{ steps.timestampid.outputs.timestamp }}/ --recursive

      - name: Write URL in summary
        run: echo "### [Allure results] http://mkuznetsov-github.s3-website.eu-north-1.amazonaws.com/report/${{ steps.timestampid.outputs.timestamp }}/index.html" >> $GITHUB_STEP_SUMMARY